### ISSUE TITLE
Is backup data of this project available ?

### ISSUE THREAD

**Issue by Cyclodex** [kontent-ai/sample-app-next-js#48]
Hi again

I am checking out this repo, to see how well **Kontent.ai** and **Next.js** would work out for us!
It looks like this is one of the most up to date repos in this context, and looks like it has quite some features covered.
Do you suggest this or maybe an other repo for checking out the possibilities of Kontent.ai and Next.js setup?

Until now I just tried out the Repo from Vercel, which worked out nicely but is probably much more basic as this setup here.
 * https://github.com/vercel/next.js/tree/canary/examples/cms-kontent-ai

I have seen an other repo from you guys, but probably also not that big and maybe outdated:
 * https://github.com/kontent-ai/boilerplate-next-js

If this repo is the right place:
I found the following in your readme:

> TBD - raise the issue, if you want the project backup

Is it possible to get a backup of the Kontent.ai project to import it?
I guess I could import that then over your [backup-manager tool](https://github.com/kontent-ai/backup-manager-js) - like I did with the Vercel example...

Cheers

**Comment by JiriLojda** [comment]
Hi @Cyclodex,

Thank you for your interest. This is the latest sample project that we are still working on. Even though it is still in preview, I recommend you give it a try, as you mentioned it is a lot more comprehensive than our other samples. 

The backup mention is rather misleading and should instead mention access to the option to create your own Kontent.ai source project. I will clarify that in the readme. It is just a button in the Kontent.ai UI that will generate the project for you.
Since the data source generator is still in preview, we enable access to it per request. If you are interested in that, please, send me the email which is connected with your Kontent.ai account and I will enable it for you. Then you will be able to generate your own sample project in your Kontent.ai account and try running this app with it as the source.

**Comment by Simply007** [comment]
Could you enable it for me too for `chrastina.ondra@gmail.com`?

**Comment by JiriLojda** [comment]
Sure @Simply007, you should be able to generate it now.

**Comment by Cyclodex** [comment]
Cool thanks @JiriLojda !

My Account on Kontent.ai is `fabian.gander[at]soulcode.ch`

**Comment by JiriLojda** [comment]
@Cyclodex You should now see 
![image](https://github.com/kontent-ai/sample-app-next-js/assets/25480503/f715c483-7f51-42a8-b445-6692199eb292)
this tile in the projects listing that you can use to generate the project. Let me know if you can't find it.

**Comment by Cyclodex** [comment]
Works and I already created a project with it - thanks a lot!
